/*
of Product API

Documentation for Product API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package products_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DataProduct type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataProduct{}

// DataProduct defines the structure for an API product
type DataProduct struct {
	Description *string `json:"description,omitempty"`
	// The ID for this product
	Id int32 `json:"id"`
	Name string `json:"name"`
	Price *float32 `json:"price,omitempty"`
	Sku string `json:"sku"`
}

type _DataProduct DataProduct

// NewDataProduct instantiates a new DataProduct object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataProduct(id int32, name string, sku string) *DataProduct {
	this := DataProduct{}
	this.Id = id
	this.Name = name
	this.Sku = sku
	return &this
}

// NewDataProductWithDefaults instantiates a new DataProduct object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataProductWithDefaults() *DataProduct {
	this := DataProduct{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *DataProduct) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataProduct) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *DataProduct) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *DataProduct) SetDescription(v string) {
	o.Description = &v
}

// GetId returns the Id field value
func (o *DataProduct) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DataProduct) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DataProduct) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *DataProduct) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DataProduct) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DataProduct) SetName(v string) {
	o.Name = v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *DataProduct) GetPrice() float32 {
	if o == nil || IsNil(o.Price) {
		var ret float32
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataProduct) GetPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *DataProduct) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given float32 and assigns it to the Price field.
func (o *DataProduct) SetPrice(v float32) {
	o.Price = &v
}

// GetSku returns the Sku field value
func (o *DataProduct) GetSku() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sku
}

// GetSkuOk returns a tuple with the Sku field value
// and a boolean to check if the value has been set.
func (o *DataProduct) GetSkuOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sku, true
}

// SetSku sets field value
func (o *DataProduct) SetSku(v string) {
	o.Sku = v
}

func (o DataProduct) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataProduct) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	toSerialize["sku"] = o.Sku
	return toSerialize, nil
}

func (o *DataProduct) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"sku",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDataProduct := _DataProduct{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDataProduct)

	if err != nil {
		return err
	}

	*o = DataProduct(varDataProduct)

	return err
}

type NullableDataProduct struct {
	value *DataProduct
	isSet bool
}

func (v NullableDataProduct) Get() *DataProduct {
	return v.value
}

func (v *NullableDataProduct) Set(val *DataProduct) {
	v.value = val
	v.isSet = true
}

func (v NullableDataProduct) IsSet() bool {
	return v.isSet
}

func (v *NullableDataProduct) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataProduct(val *DataProduct) *NullableDataProduct {
	return &NullableDataProduct{value: val, isSet: true}
}

func (v NullableDataProduct) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataProduct) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


