/*
of Product API

Documentation for Product API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package products_client

import (
	"encoding/json"
)

// checks if the HandlersGenericError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HandlersGenericError{}

// HandlersGenericError struct for HandlersGenericError
type HandlersGenericError struct {
	Message *string `json:"message,omitempty"`
}

// NewHandlersGenericError instantiates a new HandlersGenericError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHandlersGenericError() *HandlersGenericError {
	this := HandlersGenericError{}
	return &this
}

// NewHandlersGenericErrorWithDefaults instantiates a new HandlersGenericError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHandlersGenericErrorWithDefaults() *HandlersGenericError {
	this := HandlersGenericError{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *HandlersGenericError) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HandlersGenericError) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *HandlersGenericError) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *HandlersGenericError) SetMessage(v string) {
	o.Message = &v
}

func (o HandlersGenericError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HandlersGenericError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableHandlersGenericError struct {
	value *HandlersGenericError
	isSet bool
}

func (v NullableHandlersGenericError) Get() *HandlersGenericError {
	return v.value
}

func (v *NullableHandlersGenericError) Set(val *HandlersGenericError) {
	v.value = val
	v.isSet = true
}

func (v NullableHandlersGenericError) IsSet() bool {
	return v.isSet
}

func (v *NullableHandlersGenericError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHandlersGenericError(val *HandlersGenericError) *NullableHandlersGenericError {
	return &NullableHandlersGenericError{value: val, isSet: true}
}

func (v NullableHandlersGenericError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHandlersGenericError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


